### ISSUE TITLE
can read csv (position)file？

### ISSUE THREAD

**Issue by BonedDeng** [XieResearchGroup/Physics-aware-Multiplex-GNN#2]

**Comment by zetayue** [comment]
Yes, as long as your csv file contains the necessary information to be loaded as the data object in PyTorch Geometric. The current dataloaders in this repo are built to load the data format in the benchmark datasets.

**Comment by BonedDeng** [comment]
but it need smiles and 3dcoordinate as input？

**Comment by zetayue** [comment]
SMILES is not necessary since it is mainly for small molecules. Any data format (mol, pdb, sdf, etc.) that can provide 3d coordinates and chemical features to represent a 3D molecular structure is okay. The dataloader has to be modified to load your own data as the data object in PyG.
