### ISSUE TITLE
Problem with data preprocessing

### ISSUE THREAD

**Issue by bamattsson** [XieResearchGroup/Physics-aware-Multiplex-GNN#7]
Hi!

I used your repo for a bit. Thanks for sharing it! When I decided to dig deep into the preprocessing I noticed a problem from a biochemistry point of view.

In short you remove all hydrogens including the partial charges on the hydrogens but you do not account for the partial charges of the removed hydrogens. This has a large implication on the preprocessing from a biochemistry and physics point of view. For example the side chain of Lysine will appear to be negatively charge using your code whereas it should be positively charged (sine the positive charge is distributed among the hydrogens). This would mean that it is impossible for the neural network to learn the underlying biochemistry (e.g. columb forces).

To explain it referring to your code: at this [line](https://github.com/XieResearchGroup/Physics-aware-Multiplex-GNN/blob/main/utils/featurizer.py#L240) you skip all hydrogens, that in itself is not the problem. However, when you later produce the partial charge feature (see [this line](https://github.com/XieResearchGroup/Physics-aware-Multiplex-GNN/blob/main/utils/featurizer.py#L246) and [this other line](https://github.com/XieResearchGroup/Physics-aware-Multiplex-GNN/blob/main/utils/featurizer.py#L99)) you do not account for the partial charges on the hydrogens attached to the heavy atoms. This means that your partial charge feature is not meaningful from a physics point of view.

You could use the code below for example to extract partial charges from neighbouring hydrogens to a heavy atom. You could then use this in a variety of ways to fix your current or construct new features.
```
def get_hydrogen_neighbours_partialcharge(atom: openbabel.OBAtom) -> float:
    partialcharge = 0
    for neighbor in openbabel.OBAtomAtomIter(atom):
        if neighbor.GetAtomicNum() == 1:
            partialcharge += neighbor.GetPartialCharge()
    return partialcharge
```
I did try this but did not see a meaningful improvement on the test set I care about. This may indicate some other problems.

**Comment by zetayue** [comment]
Hi!

Thank you for taking the time to explore my repo and for sharing your insightful observations! I really appreciate your detailed explanation and effort in identifying potential issues.

I think your point on the implications of removing hydrogens without accounting for their partial charges makes sense. I'd like to clarify that the preprocessing code you referred to is directly adapted from another library, as noted in the [comments](https://github.com/XieResearchGroup/Physics-aware-Multiplex-GNN/blob/main/utils/featurizer.py#L1), and I didn’t originally implement it myself. The same code for getting the features has been used by previous works for binding site prediction ([Pafnucy](https://github.com/mindspore-ai/models/blob/eab643f/research/hpc/pafnucy/src/data.py), [DeepSurf](https://github.com/stemylonas/DeepSurf/blob/ff2f85d/tfbio_data.py), [PUResNet](https://github.com/jivankandel/PUResNet/blob/cb618c5/data.py)), binding affinity prediction ([SIGN](https://github.com/PaddlePaddle/PaddleHelix/blob/705c297/apps/drug_target_interaction/sign/featurizer.py)), etc. When incorporating it into this repo, I overlooked the concerns you highlighted regarding the partial charges of hydrogens. I also can’t be certain whether the original authors (or others using the same code) accounted for this issue in their applications.

I feel that considering partial charges more accurately could potentially lead to better performance on certain tasks, even if not necessarily for protein-ligand binding-related predictions. Your provided code snippet is a valuable starting point, maybe some changes in the message passing functions are needed to better address the partial charges.
